### ISSUE TITLE
Linux builds not available on conda-forge channel

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nbpresent-feedstock#3]
On the initial commit, and on the merging of the most recent feedstock, linux builds were not uploaded:
https://anaconda.org/conda-forge/nbpresent/files

Looking at the most recent build, it looks like the circleci only ran py2.7, anyway:
https://circleci.com/gh/conda-forge/nbpresent-feedstock/4

Any thoughts, @ocefpaf @jakirkham?

**Comment by jakirkham** [comment]
No idea. Are you getting an error, signal, or something that is causing it to stop?

**Comment by jakirkham** [comment]
@pelson, won't be back for a bit, but I'm going to put this one on his radar. We have seen one other feedstock run to the point of test completion and not upload anything. Though we are still unsure why that is.

**Comment by bollwyvl** [comment]
nope: the end of the 2.7 build looks normal.

Running the docker stuff locally hacked up with some more debugging to see what i can see...

**Comment by jakirkham** [comment]
FWIW it seems that the CircleCI PRs didn't run anything other than Python 2.7. So, that's a bit odd.

**Comment by bollwyvl** [comment]
Indeed!

**Comment by bollwyvl** [comment]
One meta question: why is conda-build-all not used in the docker setup?

**Comment by jakirkham** [comment]
So, `conda-build-all` is used to render feedstocks. In other words, it has been used to create all of the configuration files. Though I may not understand the motivation of the question; so, feel free to ask more questions.

**Comment by bollwyvl** [comment]
Well, specifically in [the run_docker_build template](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/run_docker_build.tmpl#L50), separate blocks are created for each of the (in this case) pythons... i thought conda-build-all would do that automagically, i.e. one call to conda-build-all vs many calls to conda build. But i imagine there is a fine reason. I had just gotten used to testing it locally that way.

Making some headway locally: basically `conda-build` is exiting non-zero without any apparent message... of course, i didn't print that return code out, so running again...

**Comment by bollwyvl** [comment]
Ok, it looks like deep under the covers, it looks like one of the following is indeed throwing an unexpected signal:
- https://github.com/jupyter/notebook/blob/master/notebook/jstest.py
- casperjs
- phantomjs

haven't determined which or what...

I am inclined to drop the full test suite on linux (just bail on not `darwin`) and just check `test: {imports: whatever}` for now so i can get initial releases of these things out... thoughts on this approach?

**Comment by pelson** [comment]
https://github.com/conda-forge/erlang-feedstock/issues/1 saw a similar issue

**Comment by jakirkham** [comment]
So, I see Linux builds on conda-forge. Appears this is resolved. Should we close this?

**Comment by bollwyvl** [comment]
Yeah!
